default:
  target: default
  outputs:
    default:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USERNAME') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: "{{ env_var('DBT_DBNAME') }}"
      port: 5432
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 2